### ISSUE TITLE
USERNAME and COMPUTERNAME are mandatory

### ISSUE THREAD

**Issue by PSLLSP** [pddring/mcpi-sim#2]
Variables USERNAME and COMPUTERNAME are mandatory, without them mc.py will not start. Could be some predefined values used in the case that variables are not set?

I prepared this simple script to start mc.py at my Ubuntu computer:

psl@test:~/mcpi-sim$ cat run.sh 
#!/bin/sh

export USERNAME="user"
export COMPUTERNAME="linux"

#python mc.py
idle mc.py

When variables are not set, mc.py ends with the error:

    Controls:
        Use the mouse to look around
        Use WASD to move
        Press Space to move up
        Press Shift + Space to move down
        Press P to display the current position of the camera
        Press Q to Quit.
        
Traceback (most recent call last):
  File "mc.py", line 12, in <module>
    mc.postToChat("Hello")
  File "/home/psl/mcpi-sim/local/minecraft.py", line 457, in postToChat
    print os.environ["USERNAME"] + "@" + os.environ["COMPUTERNAME"] + ": " + msg
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'USERNAME'

**Comment by PSLLSP** [comment]
Better way to define mandatory enviromental variables is from mc.py; this is the simplest way, no checks for current values, just define them:

```python
#!/usr/bin/env python
print "Loading... please wait"

import os

os.environ['USERNAME'] = 'user'
os.environ['COMPUTERNAME'] = 'linux'

# import minecraft modules
## SIMULATOR
from local.minecraft import *
from local.block import *

# MINECRAFT PI
#from mcpi.minecraft import *
#from mcpi.block import *

# create link to minecraft game or simulator
# change 10.10.95.64 to the ip address of your raspberry pi
#mc = Minecraft.create("10.10.95.64")
mc = Minecraft.create("localhost")

# post a chat message
mc.postToChat("Hello")

# draw a stone block at (x=0, y=0, z=0)
mc.setBlock(0,0,0, STONE)
```
